# Generated by Django 3.0.7 on 2022-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
